
#General Info
result_path: '../../mesh_walker/mesh_reconstruction/'
trained_model: '../../mesh_walker/runs_aug_360_must/0078-06.01.2021..15.42__camel_horse_xyz__shrec11_16-04_a/'
#'../../mesh_walker/runs_aug_360_must/0096-12.01.2021..18.04_horse_balls_only_shrec11_16-04_a'
dataset_path: 'datasets_processed/shrec11/16-04_a/test/*.npz'


#Training params
learning_weight: 0.01
weight_threshold: 1
max_label_diff: 0.3
iterations_with_no_changes: 25
no_change_threshold: 0.01
max_iter: 100_000
iter_2_change_weight: 1_000


# Experiment params
use_sphere_or_model: 'model' #'sphere' #'model'
mesh_path: 'datasets_processed/shrec11/16-04_a/train/T295_not_changed_500.npz' # This is a horse
#'datasets_processed/shrec11/16-04_a/train/T398_not_changed_500.npz' #This is a camel


# 15 - horse 18 - balls 25 - camel
target_label: 25 
source_label: 15 
trained_only_2_classes: True


#Attack params 
loss: 'sparse_categorical_crossentropy'
attack: 'none'


# logger options
image_save_iter:  100       # How often do you want to save output images during training
image_display_iter: 100       # How often do you want to display output images during training
display_size: 15              # How many images do you want to display each time
snapshot_save_iter: 10_000    # How often do you want to save trained models
log_iter: 1                   # How often do you want to log the training stats

#Addons
generate_csv_file2label : False

#Manifold training
manifold_training: False

