
#General Info
result_path: '../../mesh_walker/horse_to_dog2/'
#'../../mesh_walker/horse_to_dog1/'
#'../../mesh_walker/camel_to_dog2/'
#'../../mesh_walker/camel_to_dog1/'
#'../../mesh_walker/dog2_to_camel/'
#'../../mesh_walker/dog2_to_horse/'

use_prev_model: True
trained_model: '../../mesh_walker/runs_aug_360_must/0000_important_runs/manifold_sparse_loss_only_30_labels'
#'../../mesh_walker/runs_aug_360_must/0000_important_runs/sparse_30_then_kl_and_sparse_4'
#'../../mesh_walker/runs_aug_360_must/0000_important_runs/manifold_sparse_loss_only_30_then_kl_div_dog1_horse'
#'../../mesh_walker/runs_aug_360_must/0000_important_runs/manifold_sparse_and_kl_30_then_2_only_manifold_dog1_dog2'
#'../../mesh_walker/runs_aug_360_must/0000_important_runs/manifold_sparse_loss_only_30_labels'
#'../../mesh_walker/runs_aug_360_must/0000_important_runs/manifold_lk_and_sparse_loss_30_labels'
#'../../mesh_walker/runs_aug_360_must/0000_important_runs/manifold_kl_loss_only_30_labels'
#'../../mesh_walker/runs_aug_360_must/0142-27.01.2021..11.04__shrec11_16-04_a' #mesh_walk regular 30 classes

#'../../mesh_walker/runs_aug_360_must/0101-18.01.2021..19.27__shrec11_16-04_a_horse_zebra_5000_faces'
#'../../mesh_walker/runs_aug_360_must/0078-06.01.2021..15.42__camel_horse_xyz__shrec11_16-04_a/'
#'../../mesh_walker/runs_aug_360_must/0096-12.01.2021..18.04_horse_balls_only_shrec11_16-04_a/'

description: "manifold training of dog1,dog2, horse and camel, after all 30"
dataset_path: 'datasets_processed/shrec11/16-04_a/test/*.npz'

job: 'shrec11'
job_part: '16-04_a'
# choose network task from: 'features_extraction', 'unsupervised_classification', 'semantic_segmentation', 'classification', 'manifold_classification'.
network_task: 'manifold_classification'

# 2 labels training params
# 15 - horse, 18 - balls, 25 - camel, 7 - dog1, 4 - dog2, 23 - woman, 1- man, 9- bird2, 29- bird1
target_label: 25
source_label: 7
chose_target_label: True

trained_only_2_classes: False
train_several_classes: True
classes_to_train: [4,7,15,25]

# Manifold params
shift_size: 1
non_zero_ratio: 2
alpha: 0.5
#'sparse_only' #'manifold_only' #'both'
sparse_or_manifold: 'both'

# Deform Training params
learning_weight: 0.0001
weight_threshold: 0.002
max_label_diff: 0.0001
iterations_with_no_changes: 25
no_change_pred_threshold: 0.0003
pred_close_enough_to_target: 0.9
max_iter: 30_000
iter_2_change_weight: 1_000
show_model_every: 30_001

walk_len: 2000
use_sphere_or_model: 'model' #'sphere' #'model'


use_last: False
mesh_path: 'datasets_processed/shrec11/16-04_a/train/T398_not_changed_500.npz' #This is a camel

#'datasets_processed/shrec11_raw_5k/T398_simplified_to_5000.npz' #camel
#'datasets_processed/shrec11_raw_5k/T295_simplified_to_5000.npz' #horse

#500
#'datasets_processed/shrec11/16-04_a/train/T136_not_changed_500.npz' #dog1
#'datasets_processed/shrec11/16-04_a/train/T295_not_changed_500.npz' # This is a horse+
#'datasets_processed/shrec11/16-04_a/train/T398_not_changed_500.npz' #This is a camel
#'datasets_processed/shrec11/16-04_a/train/T504_not_changed_500.npz' #dog2
#'datasets_processed/shrec11/16-04_a/train/T36_not_changed_500.npz' #woman
#'datasets_processed/shrec11/16-04_a/train/T437_not_changed_500.npz' #man


#Attack params
#'forward' - too target, 'away' - away from source, 'both' - one forward iter and one away iter, 'after' - firstly away and atfer num_iters forward
attack_direction: 'both'
thrs_iters_for_forward: 10_000
sparse_alpha: 0
kl_div_alpha: 1
mse_alpha: 0

# logger options
image_save_iter:  100       # How often do you want to save output images during training
plot_iter: 10
image_display_iter: 100       # How often do you want to display output images during training
display_size: 15              # How many images do you want to display each time
snapshot_save_iter: 10_000    # How often do you want to save trained models
log_iter: 1                   # How often do you want to log the training stats

#Addons
generate_csv_file2label : False
